CREATE DATABASE CALLCENTERDB
GO
USE CALLCENTERDB

CREATE TABLE ROLES (
	id INT IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL UNIQUE,
	activo BIT NOT NULL
)

CREATE TABLE USUARIOS (
	id INT IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	login VARCHAR(100) NOT NULL UNIQUE,
	hash_password VARCHAR(100) NOT NULL,
	rol_id INT NOT NULL FOREIGN KEY REFERENCES ROLES(id),
	activo BIT NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	img_url VARCHAR(100) NOT NULL
)

CREATE TABLE CLIENTES (
	id INT IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	telefono VARCHAR(100) NULL,
	identificacion VARCHAR(100) NULL,
	activo BIT NOT NULL,
	fecha_alta DATETIME NOT NULL
)

CREATE TABLE TIPOS_INCIDENCIA (
	id INT IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL UNIQUE,
	descripcion VARCHAR(100) NULL,
	activo BIT NOT NULL
)

CREATE TABLE PRIORIDADES (
	id INT IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL UNIQUE,
	nivel INT NOT NULL,
	activo BIT NOT NULL
)

CREATE TABLE ESTADOS_INCIDENTE (
	id INT IDENTITY PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL UNIQUE,
	activo BIT NOT NULL
)

CREATE TABLE INCIDENTES (
	id INT IDENTITY PRIMARY KEY,
	nro_reclamo VARCHAR(100) NOT NULL UNIQUE,
	descripcion_problematica VARCHAR(100) NOT NULL,
	fecha_alta DATETIME NOT NULL,
	fecha_ultima_actualizacion DATETIME NOT NULL,
	cliente_id INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(id),
	tipo_incidencia_id INT NOT NULL FOREIGN KEY REFERENCES TIPOS_INCIDENCIA(id),
	prioridad_id INT NOT NULL FOREIGN KEY REFERENCES PRIORIDADES(id),
	estado_id INT NOT NULL FOREIGN KEY REFERENCES ESTADOS_INCIDENTE(id),
	usuario_creador_id INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(id),
	usuario_asignado_id INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(id),
	dato_resolucion VARCHAR(100) NULL,
	fecha_resolucion DATETIME NULL,
	usuario_resolucion_id INT NULL FOREIGN KEY REFERENCES USUARIOS(id),
	comentario_cierre VARCHAR(100) NULL,
	fecha_cierre DATETIME NULL,
	usuario_cierre_id INT NULL FOREIGN KEY REFERENCES USUARIOS(id)
)

CREATE TABLE HISTORIAL_ESTADOS (
	id INT IDENTITY PRIMARY KEY,
	incidente_id INT NOT NULL FOREIGN KEY REFERENCES INCIDENTES(id),
	estado_anterior_id INT NOT NULL FOREIGN KEY REFERENCES ESTADOS_INCIDENTE(id),
	estado_nuevo_id INT NOT NULL FOREIGN KEY REFERENCES ESTADOS_INCIDENTE(id),
	usuario_id INT NULL FOREIGN KEY REFERENCES USUARIOS(id),
	fecha_cambio DATETIME NOT NULL,
	motivo_nota VARCHAR(100) NULL
)

CREATE TABLE COMENTARIOS_INCIDENTE (
	id INT IDENTITY PRIMARY KEY,
	incidente_id INT NOT NULL FOREIGN KEY REFERENCES INCIDENTES(id),
	usuario_id INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(id),
	comentario VARCHAR(500) NOT NULL,
	fecha_comentario DATETIME NOT NULL
)

CREATE TABLE COMENTARIOS_INCIDENTE (
    id INT IDENTITY PRIMARY KEY,
    incidente_id INT NOT NULL FOREIGN KEY REFERENCES INCIDENTES(id),
    usuario_id INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(id),
    comentario VARCHAR(500) NOT NULL,
    fecha_comentario DATETIME NOT NULL
);

